# Generated by Django 5.2.7 on 2025-10-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_article_category_alter_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary_audio',
            field=models.FileField(blank=True, null=True, upload_to='summary_audio/'),
        ),
    ]
